### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by scalpovich** [adelbs/DevTest-ISO8583#1]
hi Adbel
First congrat for this proyect. it's look helpful.
But i get issue with compilation cause by some local repo included in the pom.xml.

Kindly share the remote library in order to test your work and contribuate if necessary

**Comment by adelbs** [comment]
Hi @scalpovich ! Sorry the late response! I'm not actively maintaining this project.
You can find the binary files here:

https://github.com/adelbs/DevTest-ISO8583/releases

I'll send a new version in a couple of days (for DevTest version 15.5 and on).

I'm closing this issue. If you have any other difficulty please open another one.

Thank you!

**Comment by adelbs** [comment]
@scalpovich 
Regarding the libs:
If you use DevTest, you can find all jars in the lib/shared folder.

**Comment by scalpovich** [comment]
Hello
Thank for your revert
lib/shared folder where ? I can't see this forlder on the repo

**Comment by adelbs** [comment]
> Hello
> Thank for your revert
> lib/shared folder where ? I can't see this forlder on the repo

Are you using devtest? If so, you can find it in the instalation folder.
