### ISSUE TITLE
TPDU Header format

### ISSUE THREAD

**Issue by scalpovich** [adelbs/DevTest-ISO8583#2]
Hello
Need to send message with custom header like :
MsgLength + FixHeaderValue + ISOmsg.  where MsgLength is numeric format and has 4 as length

How can i add it

**Comment by tiagoms1** [comment]
Hello! This MsgLength is already added into the message automatically. If you play 2 instances of the component (one as server one as client) you can see in Wireshark, for example.

**Comment by tiagoms1** [comment]
issue closed
